name: CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Install dependencies
      - name: Install Dependencies
        run: npm install --legacy-peer-deps

      # Build the project
      - name: Build
        env:
          VITE_SERVER_URL: https://api.hangngachinhhang.com/api/v1
        run: npm run build
      - name: Print current directory
        run: pwd

      - name: List files in the current directory
        run: ls -la


  deploy:
    name: Deploy to VPS
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Set up SSH
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.VPS_IP }} >> ~/.ssh/known_hosts

      # Deploy artifacts to the VPS
      - name: Deploy to VPS
        run: scp -r /home/runner/work/hangngachinhhang-admin/hangngachinhhang-admin/dist/ root@${{ secrets.VPS_IP }}:/home/admin.hangngachinhhang.com
